#https://claude.ai/
import numpy as np
import struct

# ── Параметры ──────────────────────────────────────────────────────────────
RESOLUTION   = 512       # разрешение heightmap (512×512 → ~500k полигонов)
CUBE_SIZE    = 60.0      # размер грани куба в мм
BASE_HEIGHT  = 6.0       # толщина основания куба в мм
RELIEF_HEIGHT = 3.      # высота рельефа над поверхностью в мм
N_POINTS     = 13        # количество вершин звезды
STEP         = 5         # шаг связи (i → i+5), определяет рисунок
OUTPUT_FILE  = "./stl/star_cube.stl"

TAU = 2 * np.pi

def smoothstep(edge0, edge1, x):
    t = np.clip((x - edge0) / (edge1 - edge0), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)

# ── Воссоздаём логику GLSL lens() ──────────────────────────────────────────
def compute_heightmap(res):
    # координаты пикселей в пространстве [-1..1] по Y, как в шейдере
    xs = np.linspace(-1, 1, res)
    ys = np.linspace(-1, 1, res)
    px, py = np.meshgrid(xs, ys)

    result = np.zeros((res, res), dtype=np.float32)
    r0 = 0.95

    for i in range(N_POINTS):
        ax = r0 * np.cos(TAU / N_POINTS * i)
        ay = r0 * np.sin(TAU / N_POINTS * i)
        bx = r0 * np.cos(TAU / N_POINTS * (i + STEP))
        by = r0 * np.sin(TAU / N_POINTS * (i + STEP))

        cx, cy = (ax + bx) / 2.0, (ay + by) / 2.0
        nx, ny = -(by - ay), (bx - ax)          # перпендикуляр
        l = np.sqrt(nx*nx + ny*ny) / 2.0
        nx /= (l * 2.0 + 1e-10)
        ny /= (l * 2.0 + 1e-10)

        d = 0.1
        x = d * l
        y = l / d
        r = (x + y) / 2.0
        h = r - x

        c1x, c1y = cx + nx * h, cy + ny * h
        c2x, c2y = cx - nx * h, cy - ny * h

        dist1 = np.sqrt((px - c1x)**2 + (py - c1y)**2)
        dist2 = np.sqrt((px - c2x)**2 + (py - c2y)**2)
        di = np.minimum(r - dist1, r - dist2)

        hh = 0.05
        di = smoothstep(0.0, hh, di) * di
        #di = np.where(di < 0, 0.0,
        #     np.where(di < hh, (di / hh) * di, di))
        di = np.power(np.maximum(di, 0), 0.5)
        x_pw = x ** 0.5
        res_i = di / (x_pw + 1e-10)

        result = np.maximum(result, res_i)

    return np.clip(result, 0, 1)

# ── Строим грань куба как mesh ──────────────────────────────────────────────
def make_face_mesh(heightmap, size, base_h, relief_h):
    """Возвращает список треугольников (каждый = 3 точки xyz) для одной грани."""
    res = heightmap.shape[0]
    step = size / (res - 1)

    # вершины: x, y, z где z = высота
    xs = np.linspace(0, size, res)
    ys = np.linspace(0, size, res)
    gx, gy = np.meshgrid(xs, ys)
    gz = base_h + heightmap * relief_h

    triangles = []
    for row in range(res - 1):
        for col in range(res - 1):
            # два треугольника на квад
            v00 = (gx[row,   col],   gy[row,   col],   gz[row,   col])
            v10 = (gx[row+1, col],   gy[row+1, col],   gz[row+1, col])
            v01 = (gx[row,   col+1], gy[row,   col+1], gz[row,   col+1])
            v11 = (gx[row+1, col+1], gy[row+1, col+1], gz[row+1, col+1])
            triangles.append((v00, v10, v01))
            triangles.append((v10, v11, v01))
    return triangles

def flat_face(x0, y0, x1, y1, z, flip=False):
    """Плоская грань (дно или боковая стенка)."""
    if not flip:
        return [
            ((x0,y0,z),(x1,y0,z),(x0,y1,z)),
            ((x1,y0,z),(x1,y1,z),(x0,y1,z)),
        ]
    else:
        return [
            ((x0,y0,z),(x0,y1,z),(x1,y0,z)),
            ((x1,y0,z),(x0,y1,z),(x1,y1,z)),
        ]

def wall(p0, p1, p2, p3):
    """Боковая стенка из 4 точек."""
    return [
        (p0, p1, p2),
        (p1, p3, p2),
    ]

# ── Нормаль треугольника ────────────────────────────────────────────────────
def triangle_normal(t):
    a = np.array(t[0]); b = np.array(t[1]); c = np.array(t[2])
    n = np.cross(b - a, c - a)
    ln = np.linalg.norm(n)
    return n / ln if ln > 1e-10 else n

# ── Запись STL ──────────────────────────────────────────────────────────────
def write_stl(triangles, path):
    header = b"STL star cube generated by Python" + b" " * (80 - 33)
    n = len(triangles)
    with open(path, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", n))
        for tri in triangles:
            norm = triangle_normal(tri)
            f.write(struct.pack("<fff", *norm))
            for v in tri:
                f.write(struct.pack("<fff", *v))
            f.write(struct.pack("<H", 0))
    print(f"Записано {n:,} треугольников → {path}")

# ── Главная сборка ──────────────────────────────────────────────────────────
def build_cube_stl():
    print(f"Считаю heightmap {RESOLUTION}×{RESOLUTION}...")
    hm = compute_heightmap(RESOLUTION)
    print(f"  max={hm.max():.3f}  min={hm.min():.3f}")

    S = CUBE_SIZE
    B = BASE_HEIGHT
    R = RELIEF_HEIGHT
    total_h = B + R     # полная высота куба

    print("Строю верхнюю грань (рельеф)...")
    
    top = make_face_mesh(1 - hm, S, B, R)

    print("Строю дно и стенки...")
    bottom = flat_face(0, 0, S, S, 0.0, flip=True)

    # 4 боковые стенки (closed solid)
    walls = []
    walls += wall((0,0,0),(S,0,0),(0,0,total_h),(S,0,total_h))   # перед
    walls += wall((S,0,0),(S,S,0),(S,0,total_h),(S,S,total_h))   # право
    walls += wall((S,S,0),(0,S,0),(S,S,total_h),(0,S,total_h))   # зад
    walls += wall((0,S,0),(0,0,0),(0,S,total_h),(0,0,total_h))   # лево

    all_tris = top + bottom + walls
    print(f"Всего треугольников: {len(all_tris):,}")

    write_stl(all_tris, OUTPUT_FILE)
    print("Готово!")

if __name__ == "__main__":
    build_cube_stl()
