import math
import numpy as np
from stl import mesh
import argparse
from scipy.spatial import KDTree


def weld_vertices(verts: np.ndarray, eps: float = 1e-4):
    """
    Сливает вершины которые ближе eps друг к другу.
    Возвращает новый массив вершин и индексы для каждой старой вершины.
    """
    tree = KDTree(verts)
    
    n = len(verts)
    mapping = np.full(n, -1, dtype=int)  # старый индекс → новый
    new_verts = []
    new_idx = 0

    for i in range(n):
        if mapping[i] != -1:
            continue
        # все вершины в радиусе eps
        neighbours = tree.query_ball_point(verts[i], eps)
        for j in neighbours:
            if mapping[j] == -1:
                mapping[j] = new_idx
        new_verts.append(verts[i])
        new_idx += 1

    return np.array(new_verts), mapping


def compute_face_normals_from_welded(new_verts: np.ndarray, indices: np.ndarray):
    """
    Пересчитывает нормали по сваренным вершинам.
    indices: (N*3,) — индексы в new_verts для каждой вершины каждого треугольника
    """
    n_faces = len(indices) // 3
    i0 = indices[0::3]
    i1 = indices[1::3]
    i2 = indices[2::3]

    v0 = new_verts[i0]
    v1 = new_verts[i1]
    v2 = new_verts[i2]

    normals = np.cross(v1 - v0, v2 - v0)
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    lengths = np.where(lengths == 0, 1, lengths)
    normals = normals / lengths

    return np.repeat(normals, 3, axis=0)  # (N*3, 3)


def compute_uvs_with_seam(vertices: np.ndarray, normals: np.ndarray, h1: float, h2: float):
    x = vertices[:, 0]
    y = vertices[:, 1]
    z = vertices[:, 2]

    dot = x * normals[:, 0] + y * normals[:, 1]
    mask = (z >= h1) & (z <= h2) & (dot >= 0)

    u_raw = np.where(mask, (np.arctan2(y, x) + math.tau) % math.tau / math.tau, 0.0)
    v     = np.where(mask, (z - h1) / (h2 - h1), 0.0)

    n_faces = len(vertices) // 3
    u = u_raw.copy()

    for i in range(n_faces):
        i0, i1, i2 = i*3, i*3+1, i*3+2
        if not (mask[i0] and mask[i1] and mask[i2]):
            continue
        tri_u = u_raw[[i0, i1, i2]]
        if np.max(tri_u) - np.min(tri_u) > 0.5:
            for idx in [i0, i1, i2]:
                if u_raw[idx] < 0.5:
                    u[idx] = u_raw[idx] + 1.0

    return np.stack([u, v], axis=1), mask


def stl_to_obj_with_uv(stl_path: str, obj_path: str, h1: float, h2: float, eps: float = 1e-4):
    stl_mesh = mesh.Mesh.from_file(stl_path)

    raw_verts = stl_mesh.vectors.reshape(-1, 3)  # (N*3, 3)

    print(f"   Вершин до сварки:  {len(raw_verts)}")
    new_verts, mapping = weld_vertices(raw_verts, eps=eps)
    print(f"   Вершин после сварки: {len(new_verts)}  (eps={eps})")

    # нормали считаем по сваренной топологии
    normals_per_vert = compute_face_normals_from_welded(new_verts, mapping)

    # UV считаем по сваренным вершинам (через mapping)
    verts_for_uv = new_verts[mapping]  # разворачиваем обратно в (N*3, 3)
    uvs, mask = compute_uvs_with_seam(verts_for_uv, normals_per_vert, h1, h2)

    n_faces = len(mapping) // 3

    with open(obj_path, "w") as f:
        f.write(f"# Generated by stl2obj_uv.py | h1={h1}, h2={h2}, eps={eps}\n")
        f.write("mtllib material.mtl\n")
        f.write("usemtl material\n\n")

        # пишем сваренные вершины
        for v in new_verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")

        # UV индексы остаются по старой схеме (N*3)
        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")

        valid_faces = 0
        for i in range(n_faces):
            j0, j1, j2 = i*3, i*3+1, i*3+2
            # v индексы — сваренные (mapping), vt индексы — старые (j)
            vi0, vi1, vi2 = mapping[j0]+1, mapping[j1]+1, mapping[j2]+1
            ti0, ti1, ti2 = j0+1, j1+1, j2+1

            all_valid = mask[j0] and mask[j1] and mask[j2]

            if all_valid:
                f.write(f"f {vi0}/{ti0} {vi1}/{ti1} {vi2}/{ti2}\n")
                valid_faces += 1
            else:
                f.write(f"f {vi0} {vi1} {vi2}\n")

    print(f"✅ Сохранено: {obj_path}")
    print(f"   Граней:    {n_faces}  (с UV: {valid_faces})")


def main():
    parser = argparse.ArgumentParser(
        description="STL → OBJ с UV и сваркой швов"
    )
    parser.add_argument("input",          help="Входной STL файл")
    parser.add_argument("output",         help="Выходной OBJ файл")
    parser.add_argument("h1", type=float, help="Нижняя высота (ось Z)")
    parser.add_argument("h2", type=float, help="Верхняя высота (ось Z)")
    parser.add_argument("--eps", type=float, default=1e-4,
                        help="Порог сварки вершин (по умолчанию 1e-4)")
    args = parser.parse_args()

    if args.h1 >= args.h2:
        raise ValueError("h1 должна быть меньше h2")

    stl_to_obj_with_uv(args.input, args.output, args.h1, args.h2, eps=args.eps)


def create_obj():
    finput = "./stl/flowerpot2.stl"
    foutput = "./stl/flowerpot5.obj"
    h1 = -0.7
    h2 = 1.8
    stl_to_obj_with_uv(finput, foutput, h1, h2)

#if __name__ == "__main__":
#    main()
create_obj()