#https://claude.ai/
import math
import numpy as np
from stl import mesh
import argparse


def compute_uvs_with_seam(vertices: np.ndarray, h1: float, h2: float):
    """
    Вычисляет UV для массива вершин (N*3, 3) — все вершины всех треугольников.
    Возвращает:
      uvs   — (N*3, 2) массив UV
      mask  — (N*3,) булева маска валидных вершин
    """
    x = vertices[:, 0]
    y = vertices[:, 1]
    z = vertices[:, 2]

    mask = (z >= h1) & (z <= h2)

    u_raw = np.where(mask, (np.arctan2(y, x) + math.tau) % math.tau / math.tau, 0.0)
    v     = np.where(mask, (z - h1) / (h2 - h1), 0.0)

    n_faces = len(vertices) // 3
    u = u_raw.copy()

    # Обработка шва: перебираем треугольники
    for i in range(n_faces):
        i0, i1, i2 = i*3, i*3+1, i*3+2
        if not (mask[i0] and mask[i1] and mask[i2]):
            continue

        tri_u = u_raw[[i0, i1, i2]]

        # Если в треугольнике разброс u > 0.5 — он пересекает шов
        if np.max(tri_u) - np.min(tri_u) > 0.5:
            # Вершины на «левой» стороне (u < 0.5) получают +1.0
            for idx in [i0, i1, i2]:
                if u_raw[idx] < 0.5:
                    u[idx] = u_raw[idx] + 1.0

    return np.stack([u, v], axis=1), mask


def stl_to_obj_with_uv(stl_path: str, obj_path: str, h1: float, h2: float):
    stl_mesh = mesh.Mesh.from_file(stl_path)
    verts = stl_mesh.vectors.reshape(-1, 3)   # (N*3, 3)
    n_verts = len(verts)
    n_faces = n_verts // 3

    uvs, mask = compute_uvs_with_seam(verts, h1, h2)

    with open(obj_path, "w") as f:
        f.write(f"# Generated by stl2obj_uv.py | h1={h1}, h2={h2}\n")
        f.write("mtllib material.mtl\n")
        f.write("usemtl material\n\n")

        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")

        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")

        valid_faces = 0
        for i in range(n_faces):
            i0, i1, i2 = i*3, i*3+1, i*3+2
            all_valid = mask[i0] and mask[i1] and mask[i2]

            if all_valid:
                f.write(
                    f"f {i0+1}/{i0+1} {i1+1}/{i1+1} {i2+1}/{i2+1}\n"
                )
                valid_faces += 1
            else:
                f.write(f"f {i0+1} {i1+1} {i2+1}\n")

    print(f"✅ Сохранено: {obj_path}")
    print(f"   Вершин: {n_verts}")
    print(f"   Треугольников: {n_faces} (с UV: {valid_faces})")


def main():
    parser = argparse.ArgumentParser(
        description="STL → OBJ с UV разметкой боковой поверхности (обработка шва)"
    )
    parser.add_argument("input",          help="Входной STL файл")
    parser.add_argument("output",         help="Выходной OBJ файл")
    parser.add_argument("h1", type=float, help="Нижняя высота (ось Z)")
    parser.add_argument("h2", type=float, help="Верхняя высота (ось Z)")
    args = parser.parse_args()

    if args.h1 >= args.h2:
        raise ValueError("h1 должна быть меньше h2")

    stl_to_obj_with_uv(args.input, args.output, args.h1, args.h2)

def create_obj():
    finput = "./stl/box.stl"
    foutput = "./stl/box.obj"
    h1 = 0
    h2 = 1
    stl_to_obj_with_uv(finput, foutput, h1, h2)

#if __name__ == "__main__":
#    main()
create_obj()