import math
import numpy as np
from stl import mesh
import argparse


def compute_face_normals(vectors: np.ndarray) -> np.ndarray:
    """
    Вычисляет нормали из геометрии треугольников.
    vectors: (N, 3, 3) — N треугольников, 3 вершины, 3 координаты
    Возвращает (N*3, 3) — нормаль для каждой вершины
    """
    v0 = vectors[:, 0]
    v1 = vectors[:, 1]
    v2 = vectors[:, 2]

    normals = np.cross(v1 - v0, v2 - v0)

    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    lengths = np.where(lengths == 0, 1, lengths)
    normals = normals / lengths

    # каждая нормаль повторяется для трёх вершин треугольника
    return np.repeat(normals, 3, axis=0)


def compute_uvs_with_seam(vertices: np.ndarray, normals: np.ndarray, h1: float, h2: float):
    x = vertices[:, 0]
    y = vertices[:, 1]
    z = vertices[:, 2]

    # dot(d, norm) где d = (x, y, 0) — вектор от оси Z к точке
    dot = x * normals[:, 0] + y * normals[:, 1]

    mask = (z >= h1) & (z <= h2) & (dot >= 0)

    u_raw = np.where(mask, (np.arctan2(y, x) + math.tau) % math.tau / math.tau, 0.0)
    v     = np.where(mask, (z - h1) / (h2 - h1), 0.0)

    n_faces = len(vertices) // 3
    u = u_raw.copy()

    for i in range(n_faces):
        i0, i1, i2 = i*3, i*3+1, i*3+2
        if not (mask[i0] and mask[i1] and mask[i2]):
            continue
        tri_u = u_raw[[i0, i1, i2]]
        if np.max(tri_u) - np.min(tri_u) > 0.5:
            for idx in [i0, i1, i2]:
                if u_raw[idx] < 0.5:
                    u[idx] = u_raw[idx] + 1.0

    return np.stack([u, v], axis=1), mask


def stl_to_obj_with_uv(stl_path: str, obj_path: str, h1: float, h2: float):
    stl_mesh = mesh.Mesh.from_file(stl_path)

    verts   = stl_mesh.vectors.reshape(-1, 3)       # (N*3, 3)
    normals = compute_face_normals(stl_mesh.vectors) # (N*3, 3)

    n_verts = len(verts)
    n_faces = n_verts // 3

    uvs, mask = compute_uvs_with_seam(verts, normals, h1, h2)

    with open(obj_path, "w") as f:
        f.write(f"# Generated by stl2obj_uv.py | h1={h1}, h2={h2}\n")
        f.write("mtllib material.mtl\n")
        f.write("usemtl material\n\n")

        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")

        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")

        valid_faces = 0
        for i in range(n_faces):
            i0, i1, i2 = i*3, i*3+1, i*3+2
            all_valid = mask[i0] and mask[i1] and mask[i2]

            if all_valid:
                f.write(
                    f"f {i0+1}/{i0+1} {i1+1}/{i1+1} {i2+1}/{i2+1}\n"
                )
                valid_faces += 1
            else:
                f.write(f"f {i0+1} {i1+1} {i2+1}\n")

    print(f"✅ Сохранено: {obj_path}")
    print(f"   Вершин:    {n_verts}")
    print(f"   Граней:    {n_faces}  (с UV: {valid_faces})")


def main():
    parser = argparse.ArgumentParser(
        description="STL → OBJ с UV только на внешней поверхности"
    )
    parser.add_argument("input",          help="Входной STL файл")
    parser.add_argument("output",         help="Выходной OBJ файл")
    parser.add_argument("h1", type=float, help="Нижняя высота (ось Z)")
    parser.add_argument("h2", type=float, help="Верхняя высота (ось Z)")
    args = parser.parse_args()

    if args.h1 >= args.h2:
        raise ValueError("h1 должна быть меньше h2")

    stl_to_obj_with_uv(args.input, args.output, args.h1, args.h2)


def create_obj():
    finput = "./stl/larme2.stl"
    foutput = "./stl/larme2.obj"
    h1 = 0.05
    h2 = 1.6
    stl_to_obj_with_uv(finput, foutput, h1, h2)

#if __name__ == "__main__":
#    main()
create_obj()